version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  private-test-fn:
    lang: go
    handler: ./private-test-fn
    image: ghcr.io/alexellis/private-test-fn:0.0.2

configuration:
  templates:
    - name: go
